### ISSUE TITLE
pre-commit auto update hook fails and project creation is aborted

### ISSUE THREAD

**Issue by Zethson** [scverse/cookiecutter-scverse#253]
```                                                                                                   (base) 11:30:02
⋊> ~/PycharmProjects cruft create https://github.com/scverse/cookiecutter-scverse                                                                                             (base) 11:30:02
  [1/8] project_name (project-name): foundational-ukb
  [2/8] package_name (foundational_ukb): 
  [3/8] project_description (A very interesting piece of code): Foundational model of the UKB
  [4/8] author_full_name (Your Name): Lukas Heumos
  [5/8] author_email (yourname@example.com): lukas.heumos@posteo.net
  [6/8] github_user (your_github_username): theislab
  [7/8] project_repo (https://github.com/theislab/foundational-ukb): 
  [8/8] Select license
    1 - MIT License
    2 - BSD 2-Clause License
    3 - BSD 3-Clause License
    4 - Apache License Version 2.0
    5 - GNU General Public License Version 3
    6 - Unlicense
    Choose from [1/2/3/4/5/6] (1): 4
Initialized empty Git repository in /home/zeth/PycharmProjects/foundational-ukb/.git/
Updating https://github.com/psf/black ... 
==> File /home/zeth/.cache/pre-commit/repobvfcllby/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Updating https://github.com/asottile/blacken-docs ... already up to date.
Updating https://github.com/pre-commit/mirrors-prettier ... updating v3.1.0 -> v4.0.0-alpha.3-1.
Updating https://github.com/astral-sh/ruff-pre-commit ... updating v0.1.6 -> v0.1.7.
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Traceback (most recent call last):
  File "/tmp/tmpr51n4pc1.py", line 11, in <module>
    run("pre-commit autoupdate -c .pre-commit-config.yaml".split(), check=True)
  File "/home/zeth/miniconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pre-commit', 'autoupdate', '-c', '.pre-commit-config.yaml']' returned non-zero exit status 1.
Stopping generation because post_gen_project hook script didn't exit successfully
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cruft/_cli.py:107 in create                    │
│                                                                                                  │
│   104 │   │   None, "--skip", show_default=False, help="Default files/pattern to skip on upda    │
│   105 │   ),                                                                                     │
│   106 ) -> None:                                                                                 │
│ ❱ 107 │   _commands.create(                                                                      │
│   108 │   │   template_git_url,                                                                  │
│   109 │   │   output_dir=output_dir,                                                             │
│   110 │   │   config_file=config_file,                                                           │
│                                                                                                  │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                      │
│ │            checkout = None                                              │                      │
│ │         config_file = None                                              │                      │
│ │      default_config = False                                             │                      │
│ │           directory = None                                              │                      │
│ │       extra_context = '{}'                                              │                      │
│ │            no_input = False                                             │                      │
│ │          output_dir = PosixPath('.')                                    │                      │
│ │ overwrite_if_exists = False                                             │                      │
│ │                skip = []                                                │                      │
│ │    template_git_url = 'https://github.com/scverse/cookiecutter-scverse' │                      │
│ ╰─────────────────────────────────────────────────────────────────────────╯                      │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cruft/_commands/utils/__init__.py:14 in        │
│ wrapper                                                                                          │
│                                                                                                  │
│   11 │   │   def decorator(f):                                                                   │
│   12 │   │   │   @wraps(f)                                                                       │
│   13 │   │   │   def wrapper(*args, **kwargs):                                                   │
│ ❱ 14 │   │   │   │   return f(*args, **kwargs)                                                   │
│   15 │   │   │                                                                                   │
│   16 │   │   │   return wrapper                                                                  │
│   17                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │   args = ('https://github.com/scverse/cookiecutter-scverse',) │                                │
│ │      f = <function create at 0x7f27f13b0790>                  │                                │
│ │ kwargs = {                                                    │                                │
│ │          │   'output_dir': PosixPath('.'),                    │                                │
│ │          │   'config_file': None,                             │                                │
│ │          │   'default_config': False,                         │                                │
│ │          │   'extra_context': {},                             │                                │
│ │          │   'no_input': False,                               │                                │
│ │          │   'directory': None,                               │                                │
│ │          │   'checkout': None,                                │                                │
│ │          │   'overwrite_if_exists': False,                    │                                │
│ │          │   'skip': []                                       │                                │
│ │          }                                                    │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cruft/_commands/create.py:46 in create         │
│                                                                                                  │
│   43 │   │   │   )                                                                               │
│   44 │   │                                                                                       │
│   45 │   │   project_dir = Path(                                                                 │
│ ❱ 46 │   │   │   generate_files(                                                                 │
│   47 │   │   │   │   repo_dir=cookiecutter_template_dir,                                         │
│   48 │   │   │   │   context=context,                                                            │
│   49 │   │   │   │   overwrite_if_exists=overwrite_if_exists,                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                      checkout = None                                                         │ │
│ │                   config_file = None                                                         │ │
│ │                       context = OrderedDict([('cookiecutter', OrderedDict([('project_name',  │ │
│ │                                 'foundational-ukb'), ('package_name', 'foundational_ukb'),   │ │
│ │                                 ('project_description', 'Foundational model of the UKB'),    │ │
│ │                                 ('author_full_name', 'Lukas Heumos'), ('author_email',       │ │
│ │                                 'lukas.heumos@posteo.net'), ('github_user', 'theislab'),     │ │
│ │                                 ('project_repo',                                             │ │
│ │                                 'https://github.com/theislab/foundational-ukb'), ('license', │ │
│ │                                 'Apache License Version 2.0'), ('_copy_without_render',      │ │
│ │                                 ['.github/workflows/**.yaml',                                │ │
│ │                                 'docs/_templates/autosummary/**.rst']), ('_render_devdocs',  │ │
│ │                                 False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',  │ │
│ │                                 True), ('trim_blocks', True)])), ('_template',               │ │
│ │                                 'https://github.com/scverse/cookiecutter-scverse')]))])      │ │
│ │     cookiecutter_template_dir = PosixPath('/tmp/tmp524zzfuy')                                │ │
│ │ cookiecutter_template_dir_str = '/tmp/tmp524zzfuy'                                           │ │
│ │                default_config = False                                                        │ │
│ │                     directory = None                                                         │ │
│ │                 extra_context = {}                                                           │ │
│ │                   last_commit = '8e96abb5c3e2d5078c44713958da672711cf2a48'                   │ │
│ │                      no_input = False                                                        │ │
│ │                    output_dir = PosixPath('.')                                               │ │
│ │           overwrite_if_exists = False                                                        │ │
│ │                          repo = <git.repo.base.Repo '/tmp/tmp524zzfuy/.git'>                 │ │
│ │                          skip = []                                                           │ │
│ │              template_git_url = 'https://github.com/scverse/cookiecutter-scverse'            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cookiecutter/generate.py:413 in generate_files │
│                                                                                                  │
│   410 │   │   │   │   │   raise UndefinedVariableInTemplate(msg, err, context) from err          │
│   411 │                                                                                          │
│   412 │   if accept_hooks:                                                                       │
│ ❱ 413 │   │   run_hook_from_repo_dir(                                                            │
│   414 │   │   │   repo_dir,                                                                      │
│   415 │   │   │   'post_gen_project',                                                            │
│   416 │   │   │   project_dir,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              accept_hooks = True                                                             │ │
│ │                   context = OrderedDict([('cookiecutter', OrderedDict([('project_name',      │ │
│ │                             'foundational-ukb'), ('package_name', 'foundational_ukb'),       │ │
│ │                             ('project_description', 'Foundational model of the UKB'),        │ │
│ │                             ('author_full_name', 'Lukas Heumos'), ('author_email',           │ │
│ │                             'lukas.heumos@posteo.net'), ('github_user', 'theislab'),         │ │
│ │                             ('project_repo',                                                 │ │
│ │                             'https://github.com/theislab/foundational-ukb'), ('license',     │ │
│ │                             'Apache License Version 2.0'), ('_copy_without_render',          │ │
│ │                             ['.github/workflows/**.yaml',                                    │ │
│ │                             'docs/_templates/autosummary/**.rst']), ('_render_devdocs',      │ │
│ │                             False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',      │ │
│ │                             True), ('trim_blocks', True)])), ('_template',                   │ │
│ │                             'https://github.com/scverse/cookiecutter-scverse')]))])          │ │
│ │                 copy_dirs = []                                                               │ │
│ │                         d = 'tl'                                                             │ │
│ │                        d_ = 'src/{{cookiecutter.package_name}}/tl'                           │ │
│ │ delete_project_on_failure = True                                                             │ │
│ │                      dirs = []                                                               │ │
│ │                       env = <cookiecutter.environment.StrictEnvironment object at            │ │
│ │                             0x7f27f126b760>                                                  │ │
│ │                   envvars = OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])    │ │
│ │                         f = 'test_basic.py'                                                  │ │
│ │                     files = ['test_basic.py']                                                │ │
│ │                    infile = 'tests/test_basic.py'                                            │ │
│ │   keep_project_on_failure = False                                                            │ │
│ │                   outfile = '/home/zeth/PycharmProjects/foundational-ukb/docs/_templates/au… │ │
│ │          outfile_rendered = 'docs/_templates/autosummary/class.rst'                          │ │
│ │              outfile_tmpl = <Template memory:7f27f0c4b640>                                   │ │
│ │                output_dir = '.'                                                              │ │
│ │  output_directory_created = True                                                             │ │
│ │       overwrite_if_exists = False                                                            │ │
│ │               project_dir = '/home/zeth/PycharmProjects/foundational-ukb'                    │ │
│ │               render_dirs = []                                                               │ │
│ │                  repo_dir = PosixPath('/tmp/tmp524zzfuy')                                    │ │
│ │                      root = './tests'                                                        │ │
│ │       skip_if_file_exists = False                                                            │ │
│ │              template_dir = PosixPath('/tmp/tmp524zzfuy/{{cookiecutter.project_name}}')      │ │
│ │            unrendered_dir = '/home/zeth/PycharmProjects/foundational-ukb/./src/{{cookiecutt… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cookiecutter/hooks.py:152 in                   │
│ run_hook_from_repo_dir                                                                           │
│                                                                                                  │
│   149 │   """                                                                                    │
│   150 │   with work_in(repo_dir):                                                                │
│   151 │   │   try:                                                                               │
│ ❱ 152 │   │   │   run_hook(hook_name, project_dir, context)                                      │
│   153 │   │   except (                                                                           │
│   154 │   │   │   FailedHookException,                                                           │
│   155 │   │   │   UndefinedError,                                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                   context = OrderedDict([('cookiecutter', OrderedDict([('project_name',      │ │
│ │                             'foundational-ukb'), ('package_name', 'foundational_ukb'),       │ │
│ │                             ('project_description', 'Foundational model of the UKB'),        │ │
│ │                             ('author_full_name', 'Lukas Heumos'), ('author_email',           │ │
│ │                             'lukas.heumos@posteo.net'), ('github_user', 'theislab'),         │ │
│ │                             ('project_repo',                                                 │ │
│ │                             'https://github.com/theislab/foundational-ukb'), ('license',     │ │
│ │                             'Apache License Version 2.0'), ('_copy_without_render',          │ │
│ │                             ['.github/workflows/**.yaml',                                    │ │
│ │                             'docs/_templates/autosummary/**.rst']), ('_render_devdocs',      │ │
│ │                             False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',      │ │
│ │                             True), ('trim_blocks', True)])), ('_template',                   │ │
│ │                             'https://github.com/scverse/cookiecutter-scverse')]))])          │ │
│ │ delete_project_on_failure = True                                                             │ │
│ │                 hook_name = 'post_gen_project'                                               │ │
│ │               project_dir = '/home/zeth/PycharmProjects/foundational-ukb'                    │ │
│ │                  repo_dir = PosixPath('/tmp/tmp524zzfuy')                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cookiecutter/hooks.py:135 in run_hook          │
│                                                                                                  │
│   132 │   │   return                                                                             │
│   133 │   logger.debug('Running hook %s', hook_name)                                             │
│   134 │   for script in scripts:                                                                 │
│ ❱ 135 │   │   run_script_with_context(script, project_dir, context)                              │
│   136                                                                                            │
│   137                                                                                            │
│   138 def run_hook_from_repo_dir(                                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     context = OrderedDict([('cookiecutter', OrderedDict([('project_name',                    │ │
│ │               'foundational-ukb'), ('package_name', 'foundational_ukb'),                     │ │
│ │               ('project_description', 'Foundational model of the UKB'), ('author_full_name', │ │
│ │               'Lukas Heumos'), ('author_email', 'lukas.heumos@posteo.net'), ('github_user',  │ │
│ │               'theislab'), ('project_repo', 'https://github.com/theislab/foundational-ukb'), │ │
│ │               ('license', 'Apache License Version 2.0'), ('_copy_without_render',            │ │
│ │               ['.github/workflows/**.yaml', 'docs/_templates/autosummary/**.rst']),          │ │
│ │               ('_render_devdocs', False), ('_jinja2_env_vars',                               │ │
│ │               OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])), ('_template',  │ │
│ │               'https://github.com/scverse/cookiecutter-scverse')]))])                        │ │
│ │   hook_name = 'post_gen_project'                                                             │ │
│ │ project_dir = '/home/zeth/PycharmProjects/foundational-ukb'                                  │ │
│ │      script = '/tmp/tmp524zzfuy/hooks/post_gen_project.py'                                   │ │
│ │     scripts = ['/tmp/tmp524zzfuy/hooks/post_gen_project.py']                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cookiecutter/hooks.py:118 in                   │
│ run_script_with_context                                                                          │
│                                                                                                  │
│   115 │   │   output = template.render(**context)                                                │
│   116 │   │   temp.write(output.encode('utf-8'))                                                 │
│   117 │                                                                                          │
│ ❱ 118 │   run_script(temp.name, cwd)                                                             │
│   119                                                                                            │
│   120                                                                                            │
│   121 def run_hook(hook_name, project_dir, context):                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │           _ = '/tmp/tmp524zzfuy/hooks/post_gen_project'                                      │ │
│ │    contents = '#!/bin/env python3\nfrom subprocess import run\nfrom pathlib import Path\n\n# │ │
│ │               Post p'+3603                                                                   │ │
│ │     context = OrderedDict([('cookiecutter', OrderedDict([('project_name',                    │ │
│ │               'foundational-ukb'), ('package_name', 'foundational_ukb'),                     │ │
│ │               ('project_description', 'Foundational model of the UKB'), ('author_full_name', │ │
│ │               'Lukas Heumos'), ('author_email', 'lukas.heumos@posteo.net'), ('github_user',  │ │
│ │               'theislab'), ('project_repo', 'https://github.com/theislab/foundational-ukb'), │ │
│ │               ('license', 'Apache License Version 2.0'), ('_copy_without_render',            │ │
│ │               ['.github/workflows/**.yaml', 'docs/_templates/autosummary/**.rst']),          │ │
│ │               ('_render_devdocs', False), ('_jinja2_env_vars',                               │ │
│ │               OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])), ('_template',  │ │
│ │               'https://github.com/scverse/cookiecutter-scverse')]))])                        │ │
│ │         cwd = '/home/zeth/PycharmProjects/foundational-ukb'                                  │ │
│ │         env = <cookiecutter.environment.StrictEnvironment object at 0x7f27f0beb0a0>          │ │
│ │   extension = '.py'                                                                          │ │
│ │        file = <_io.TextIOWrapper name='/tmp/tmp524zzfuy/hooks/post_gen_project.py' mode='r'  │ │
│ │               encoding='utf-8'>                                                              │ │
│ │      output = '#!/bin/env python3\nfrom subprocess import run\nfrom pathlib import Path\n\n# │ │
│ │               Post p'+3551                                                                   │ │
│ │ script_path = '/tmp/tmp524zzfuy/hooks/post_gen_project.py'                                   │ │
│ │        temp = <tempfile._TemporaryFileWrapper object at 0x7f27f0beb490>                      │ │
│ │    template = <Template memory:7f27f0c2ff70>                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/zeth/miniconda3/lib/python3.9/site-packages/cookiecutter/hooks.py:89 in run_script         │
│                                                                                                  │
│    86 │   │   proc = subprocess.Popen(script_command, shell=run_thru_shell, cwd=cwd)  # nosec    │
│    87 │   │   exit_status = proc.wait()                                                          │
│    88 │   │   if exit_status != EXIT_SUCCESS:                                                    │
│ ❱  89 │   │   │   raise FailedHookException(                                                     │
│    90 │   │   │   │   f'Hook script failed (exit status: {exit_status})'                         │
│    91 │   │   │   )                                                                              │
│    92 │   except OSError as err:                                                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            cwd = '/home/zeth/PycharmProjects/foundational-ukb'                               │ │
│ │    exit_status = 1                                                                           │ │
│ │           proc = <Popen: returncode: 1 args: ['/home/zeth/miniconda3/bin/python3.9',         │ │
│ │                  '/tmp/tm...>                                                                │ │
│ │ run_thru_shell = False                                                                       │ │
│ │ script_command = ['/home/zeth/miniconda3/bin/python3.9', '/tmp/tmpr51n4pc1.py']              │ │
│ │    script_path = '/tmp/tmpr51n4pc1.py'                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FailedHookException: Hook script failed (exit status: 1)
```

**Comment by Zethson** [comment]
Updating my pre-commit version to the latest one solved this issue.
