### ISSUE TITLE
'Hook script failed' when creating project from template

### ISSUE THREAD

**Issue by LevyNat** [scverse/cookiecutter-scverse#264]
Hi, I have an error when I run cruft create from my server. Here is the command then the stack trace: 

```
(scvi) nathanlevy@adams-workstation:~$ cruft create https://github.com/scverse/cookiecutter-scverse
  [1/8] project_name (project-name): Template \\
  [2/8] package_name (template): template \\
  [3/8] project_description (A very interesting piece of code): template
  [4/8] author_full_name (Your Name): Nathan Template
  [5/8] author_email (yourname@example.com): yourname@example.com
  [6/8] github_user (your_github_username): templatename
  [7/8] project_repo (https://github.com/templatename/Template): 
  [8/8] Select license
    1 - MIT License
    2 - BSD 2-Clause License
    3 - BSD 3-Clause License
    4 - Apache License Version 2.0
    5 - GNU General Public License Version 3
    6 - Unlicense
    Choose from [1/2/3/4/5/6] (1): 1


error: unknown option `initial-branch=main'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree



Traceback (most recent call last):
  File "/tmp/tmp4oibtdug.py", line 4, in <module>
    run("git init --initial-branch=main .".split(), check=True)
  File "/home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'init', '--initial-branch=main', '.']' returned non-zero exit status 129.
Stopping generation because pre_gen_project hook script didn't exit successfully
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cruft/_cli.py:107 in create   │
│                                                                                                  │
│   104 │   │   None, "--skip", show_default=False, help="Default files/pattern to skip on updat   │
│   105 │   ),                                                                                     │
│   106 ) -> None:                                                                                 │
│ ❱ 107 │   _commands.create(                                                                      │
│   108 │   │   template_git_url,                                                                  │
│   109 │   │   output_dir=output_dir,                                                             │
│   110 │   │   config_file=config_file,                                                           │
│                                                                                                  │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                      │
│ │            checkout = None                                              │                      │
│ │         config_file = None                                              │                      │
│ │      default_config = False                                             │                      │
│ │           directory = None                                              │                      │
│ │       extra_context = '{}'                                              │                      │
│ │            no_input = False                                             │                      │
│ │          output_dir = PosixPath('.')                                    │                      │
│ │ overwrite_if_exists = False                                             │                      │
│ │                skip = []                                                │                      │
│ │    template_git_url = 'https://github.com/scverse/cookiecutter-scverse' │                      │
│ ╰─────────────────────────────────────────────────────────────────────────╯                      │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cruft/_commands/utils/__init_ │
│ _.py:14 in wrapper                                                                               │
│                                                                                                  │
│   11 │   │   def decorator(f):                                                                   │
│   12 │   │   │   @wraps(f)                                                                       │
│   13 │   │   │   def wrapper(*args, **kwargs):                                                   │
│ ❱ 14 │   │   │   │   return f(*args, **kwargs)                                                   │
│   15 │   │   │                                                                                   │
│   16 │   │   │   return wrapper                                                                  │
│   17                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │   args = ('https://github.com/scverse/cookiecutter-scverse',) │                                │
│ │      f = <function create at 0x7f7e7c239940>                  │                                │
│ │ kwargs = {                                                    │                                │
│ │          │   'output_dir': PosixPath('.'),                    │                                │
│ │          │   'config_file': None,                             │                                │
│ │          │   'default_config': False,                         │                                │
│ │          │   'extra_context': {},                             │                                │
│ │          │   'no_input': False,                               │                                │
│ │          │   'directory': None,                               │                                │
│ │          │   'checkout': None,                                │                                │
│ │          │   'overwrite_if_exists': False,                    │                                │
│ │          │   'skip': []                                       │                                │
│ │          }                                                    │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cruft/_commands/create.py:46  │
│ in create                                                                                        │
│                                                                                                  │
│   43 │   │   │   )                                                                               │
│   44 │   │                                                                                       │
│   45 │   │   project_dir = Path(                                                                 │
│ ❱ 46 │   │   │   generate_files(                                                                 │
│   47 │   │   │   │   repo_dir=cookiecutter_template_dir,                                         │
│   48 │   │   │   │   context=context,                                                            │
│   49 │   │   │   │   overwrite_if_exists=overwrite_if_exists,                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                      checkout = None                                                         │ │
│ │                   config_file = None                                                         │ │
│ │                       context = OrderedDict([('cookiecutter', OrderedDict([('project_name',  │ │
│ │                                 'Template'), ('package_name', 'template'),                   │ │
│ │                                 ('project_description', 'template'), ('author_full_name',    │ │
│ │                                 'Nathan Template'), ('author_email',                         │ │
│ │                                 'yourname@example.com'), ('github_user', 'templatename'),    │ │
│ │                                 ('project_repo',                                             │ │
│ │                                 'https://github.com/templatename/Template'), ('license',     │ │
│ │                                 'MIT License'), ('_copy_without_render',                     │ │
│ │                                 ['.github/workflows/build.yaml',                             │ │
│ │                                 '.github/workflows/test.yaml',                               │ │
│ │                                 'docs/_templates/autosummary/**.rst']), ('_render_devdocs',  │ │
│ │                                 False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',  │ │
│ │                                 True), ('trim_blocks', True)])), ('_template',               │ │
│ │                                 'https://github.com/scverse/cookiecutter-scverse')]))])      │ │
│ │     cookiecutter_template_dir = PosixPath('/tmp/tmp8oo1ukl7')                                │ │
│ │ cookiecutter_template_dir_str = '/tmp/tmp8oo1ukl7'                                           │ │
│ │                default_config = False                                                        │ │
│ │                     directory = None                                                         │ │
│ │                 extra_context = {}                                                           │ │
│ │                   last_commit = '722725204d70783354e7a27a6d49220e6357176a'                   │ │
│ │                      no_input = False                                                        │ │
│ │                    output_dir = PosixPath('.')                                               │ │
│ │           overwrite_if_exists = False                                                        │ │
│ │                          repo = <git.repo.base.Repo '/tmp/tmp8oo1ukl7/.git'>                 │ │
│ │                          skip = []                                                           │ │
│ │              template_git_url = 'https://github.com/scverse/cookiecutter-scverse'            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cookiecutter/generate.py:343  │
│ in generate_files                                                                                │
│                                                                                                  │
│   340 │   delete_project_on_failure = output_directory_created and not keep_project_on_failure   │
│   341 │                                                                                          │
│   342 │   if accept_hooks:                                                                       │
│ ❱ 343 │   │   run_hook_from_repo_dir(                                                            │
│   344 │   │   │   repo_dir, 'pre_gen_project', project_dir, context, delete_project_on_failure   │
│   345 │   │   )                                                                                  │
│   346                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              accept_hooks = True                                                             │ │
│ │                   context = OrderedDict([('cookiecutter', OrderedDict([('project_name',      │ │
│ │                             'Template'), ('package_name', 'template'),                       │ │
│ │                             ('project_description', 'template'), ('author_full_name',        │ │
│ │                             'Nathan Template'), ('author_email', 'yourname@example.com'),    │ │
│ │                             ('github_user', 'templatename'), ('project_repo',                │ │
│ │                             'https://github.com/templatename/Template'), ('license', 'MIT    │ │
│ │                             License'), ('_copy_without_render',                              │ │
│ │                             ['.github/workflows/build.yaml', '.github/workflows/test.yaml',  │ │
│ │                             'docs/_templates/autosummary/**.rst']), ('_render_devdocs',      │ │
│ │                             False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',      │ │
│ │                             True), ('trim_blocks', True)])), ('_template',                   │ │
│ │                             'https://github.com/scverse/cookiecutter-scverse')]))])          │ │
│ │ delete_project_on_failure = True                                                             │ │
│ │                       env = <cookiecutter.environment.StrictEnvironment object at            │ │
│ │                             0x7f7e7d204110>                                                  │ │
│ │                   envvars = OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])    │ │
│ │   keep_project_on_failure = False                                                            │ │
│ │                output_dir = '.'                                                              │ │
│ │  output_directory_created = True                                                             │ │
│ │       overwrite_if_exists = False                                                            │ │
│ │               project_dir = '/home/nathanlevy/Template'                                      │ │
│ │                  repo_dir = PosixPath('/tmp/tmp8oo1ukl7')                                    │ │
│ │       skip_if_file_exists = False                                                            │ │
│ │              template_dir = PosixPath('/tmp/tmp8oo1ukl7/{{cookiecutter.project_name}}')      │ │
│ │            unrendered_dir = '{{cookiecutter.project_name}}'                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cookiecutter/hooks.py:152 in  │
│ run_hook_from_repo_dir                                                                           │
│                                                                                                  │
│   149 │   """                                                                                    │
│   150 │   with work_in(repo_dir):                                                                │
│   151 │   │   try:                                                                               │
│ ❱ 152 │   │   │   run_hook(hook_name, project_dir, context)                                      │
│   153 │   │   except (                                                                           │
│   154 │   │   │   FailedHookException,                                                           │
│   155 │   │   │   UndefinedError,                                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                   context = OrderedDict([('cookiecutter', OrderedDict([('project_name',      │ │
│ │                             'Template'), ('package_name', 'template'),                       │ │
│ │                             ('project_description', 'template'), ('author_full_name',        │ │
│ │                             'Nathan Template'), ('author_email', 'yourname@example.com'),    │ │
│ │                             ('github_user', 'templatename'), ('project_repo',                │ │
│ │                             'https://github.com/templatename/Template'), ('license', 'MIT    │ │
│ │                             License'), ('_copy_without_render',                              │ │
│ │                             ['.github/workflows/build.yaml', '.github/workflows/test.yaml',  │ │
│ │                             'docs/_templates/autosummary/**.rst']), ('_render_devdocs',      │ │
│ │                             False), ('_jinja2_env_vars', OrderedDict([('lstrip_blocks',      │ │
│ │                             True), ('trim_blocks', True)])), ('_template',                   │ │
│ │                             'https://github.com/scverse/cookiecutter-scverse')]))])          │ │
│ │ delete_project_on_failure = True                                                             │ │
│ │                 hook_name = 'pre_gen_project'                                                │ │
│ │               project_dir = '/home/nathanlevy/Template'                                      │ │
│ │                  repo_dir = PosixPath('/tmp/tmp8oo1ukl7')                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cookiecutter/hooks.py:135 in  │
│ run_hook                                                                                         │
│                                                                                                  │
│   132 │   │   return                                                                             │
│   133 │   logger.debug('Running hook %s', hook_name)                                             │
│   134 │   for script in scripts:                                                                 │
│ ❱ 135 │   │   run_script_with_context(script, project_dir, context)                              │
│   136                                                                                            │
│   137                                                                                            │
│   138 def run_hook_from_repo_dir(                                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     context = OrderedDict([('cookiecutter', OrderedDict([('project_name', 'Template'),       │ │
│ │               ('package_name', 'template'), ('project_description', 'template'),             │ │
│ │               ('author_full_name', 'Nathan Template'), ('author_email',                      │ │
│ │               'yourname@example.com'), ('github_user', 'templatename'), ('project_repo',     │ │
│ │               'https://github.com/templatename/Template'), ('license', 'MIT License'),       │ │
│ │               ('_copy_without_render', ['.github/workflows/build.yaml',                      │ │
│ │               '.github/workflows/test.yaml', 'docs/_templates/autosummary/**.rst']),         │ │
│ │               ('_render_devdocs', False), ('_jinja2_env_vars',                               │ │
│ │               OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])), ('_template',  │ │
│ │               'https://github.com/scverse/cookiecutter-scverse')]))])                        │ │
│ │   hook_name = 'pre_gen_project'                                                              │ │
│ │ project_dir = '/home/nathanlevy/Template'                                                    │ │
│ │      script = '/tmp/tmp8oo1ukl7/hooks/pre_gen_project.py'                                    │ │
│ │     scripts = ['/tmp/tmp8oo1ukl7/hooks/pre_gen_project.py']                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cookiecutter/hooks.py:118 in  │
│ run_script_with_context                                                                          │
│                                                                                                  │
│   115 │   │   output = template.render(**context)                                                │
│   116 │   │   temp.write(output.encode('utf-8'))                                                 │
│   117 │                                                                                          │
│ ❱ 118 │   run_script(temp.name, cwd)                                                             │
│   119                                                                                            │
│   120                                                                                            │
│   121 def run_hook(hook_name, project_dir, context):                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │           _ = '/tmp/tmp8oo1ukl7/hooks/pre_gen_project'                                       │ │
│ │    contents = '#!/bin/env python3\nfrom subprocess import run\n\nrun("git init               │ │
│ │               --initial-branch=ma'+27                                                        │ │
│ │     context = OrderedDict([('cookiecutter', OrderedDict([('project_name', 'Template'),       │ │
│ │               ('package_name', 'template'), ('project_description', 'template'),             │ │
│ │               ('author_full_name', 'Nathan Template'), ('author_email',                      │ │
│ │               'yourname@example.com'), ('github_user', 'templatename'), ('project_repo',     │ │
│ │               'https://github.com/templatename/Template'), ('license', 'MIT License'),       │ │
│ │               ('_copy_without_render', ['.github/workflows/build.yaml',                      │ │
│ │               '.github/workflows/test.yaml', 'docs/_templates/autosummary/**.rst']),         │ │
│ │               ('_render_devdocs', False), ('_jinja2_env_vars',                               │ │
│ │               OrderedDict([('lstrip_blocks', True), ('trim_blocks', True)])), ('_template',  │ │
│ │               'https://github.com/scverse/cookiecutter-scverse')]))])                        │ │
│ │         cwd = '/home/nathanlevy/Template'                                                    │ │
│ │         env = <cookiecutter.environment.StrictEnvironment object at 0x7f7e7b8a8890>          │ │
│ │   extension = '.py'                                                                          │ │
│ │        file = <_io.TextIOWrapper name='/tmp/tmp8oo1ukl7/hooks/pre_gen_project.py' mode='r'   │ │
│ │               encoding='utf-8'>                                                              │ │
│ │      output = '#!/bin/env python3\nfrom subprocess import run\n\nrun("git init               │ │
│ │               --initial-branch=ma'+27                                                        │ │
│ │ script_path = '/tmp/tmp8oo1ukl7/hooks/pre_gen_project.py'                                    │ │
│ │        temp = <tempfile._TemporaryFileWrapper object at 0x7f7e7b8a87d0>                      │ │
│ │    template = <Template memory:7f7e7d004890>                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/nathanlevy/mambaforge/envs/scvi/lib/python3.11/site-packages/cookiecutter/hooks.py:89 in   │
│ run_script                                                                                       │
│                                                                                                  │
│    86 │   │   proc = subprocess.Popen(script_command, shell=run_thru_shell, cwd=cwd)  # nosec    │
│    87 │   │   exit_status = proc.wait()                                                          │
│    88 │   │   if exit_status != EXIT_SUCCESS:                                                    │
│ ❱  89 │   │   │   raise FailedHookException(                                                     │
│    90 │   │   │   │   f'Hook script failed (exit status: {exit_status})'                         │
│    91 │   │   │   )                                                                              │
│    92 │   except OSError as err:                                                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            cwd = '/home/nathanlevy/Template'                                                 │ │
│ │    exit_status = 1                                                                           │ │
│ │           proc = <Popen: returncode: 1 args:                                                 │ │
│ │                  ['/home/nathanlevy/mambaforge/envs/scvi/bin/pyth...>                        │ │
│ │ run_thru_shell = False                                                                       │ │
│ │ script_command = [                                                                           │ │
│ │                  │   '/home/nathanlevy/mambaforge/envs/scvi/bin/python3.11',                 │ │
│ │                  │   '/tmp/tmp4oibtdug.py'                                                   │ │
│ │                  ]                                                                           │ │
│ │    script_path = '/tmp/tmp4oibtdug.py'                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FailedHookException: Hook script failed (exit status: 1)
(scvi) nathanlevy@adams-workstation:~$ 
```

**Comment by grst** [comment]
Any chance you are using an ancient version of git? 
We require git >=2.28 for this to work.

**Comment by flying-sheep** [comment]
Yup, that’s it. Please update to an up-to-date git.

**Comment by LevyNat** [comment]
Yes, thank you!
