### ISSUE TITLE
Deleting of created project blocked (`rmtree` and permission denied)

### ISSUE THREAD

**Issue by ilibarra** [scverse/cookiecutter-scverse#60]
During last week this was working, but I think that now this cookie-cutter is creating a directory and then deleting it, failing in case user if not executing via sudo (to be confirmed).
```
(test) rio@NB085081:cookiecutter-scverse$ cookiecutter https://github.com/scverse/cookiecutter-scverse
project_name [project-name]: test
package_name [test]: test
project_description [A very interesting piece of code]: test
author_full_name [Your Name]: Ignacio Ibarra
author_email [yourname@example.com]: ignacio.ibarra@helmholtz-muenchen.de
github_user [your_github_username]: ilibarra
project_repo [https://github.com/ilibarra/test]: https://github.com/theislab/test
Select license:
1 - MIT License
2 - BSD 2-Clause License
3 - BSD 3-Clause License
4 - Apache License Version 2.0
5 - GNU General Public License Version 3
6 - Unlicense
Choose from 1, 2, 3, 4, 5, 6 [1]: 1
error: unknown option `initial-branch=main'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

Traceback (most recent call last):
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/hooks.py", line 87, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rio/miniconda3/envs/test/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/mnt/c/Users/ignacio.ibarra/Dropbox/workspace/cookiecutter-scverse/test'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rio/miniconda3/envs/test/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/cli.py", line 152, in main
    skip_if_file_exists=skip_if_file_exists,
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/main.py", line 106, in cookiecutter
    output_dir=output_dir,
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/generate.py", line 294, in generate_files
    repo_dir, 'pre_gen_project', project_dir, context, delete_project_on_failure
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/generate.py", line 240, in _run_hook_from_repo_dir
    rmtree(project_dir)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/utils.py", line 34, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "/home/rio/miniconda3/envs/test/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/rio/miniconda3/envs/test/lib/python3.7/site-packages/cookiecutter/utils.py", line 26, in force_delete
    func(path)
PermissionError: [Errno 13] Permission denied: '/mnt/c/Users/ignacio.ibarra/Dropbox/workspace/cookiecutter-scverse/test'
```

**Comment by ilibarra** [comment]
It seems that `error: unknown option `initial-branch=main'` is due to `git` version. I use `git version 2.25.1`. What's the minimum one should consider? Thanks.
https://github.com/scverse/cookiecutter-scverse/blob/main/hooks/pre_gen_project.sh

**Comment by Zethson** [comment]
> This is solved by having the following two package versions:
> 
>     * [ ]  `git >=2.38`
> 
>     * [ ]  `python >=3.8.`
> 
> 
> Indicating / checking the versions of those two and warnings would be ideal. Which file could I modify?

I think that it could be checked here: https://github.com/scverse/cookiecutter-scverse/blob/main/hooks/pre_gen_project.sh

Basically, before the git init command is run -> check versions -> error out with helpful error messages if your conditions that you defined are not met.

**Comment by grst** [comment]
I am adding this as minimal dependencies to the README in #17. 
Is that good enough or do we want checks?

**Comment by grst** [comment]
This hasn't come up anymore... closing for now.
